name: custom_tables
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter_colorpicker: ^1.0.3
  reorderables: ^0.6.0
  flutter_bloc: ^8.1.2
  non_uniform_border: ^1.0.0
  flutter_hooks: ^0.18.6
  linked_scroll_controller: ^0.2.0
  # flutter_sticky_widgets: ^0.0.3

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
